name: ubuntu
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: START SSH
        continue-on-error: true
        run: chmod +x ubuntu && ./ubuntu
      - name: KEEP ALIVE FOR 6h
        continue-on-error: true
        run: sleep 6h
